### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by jvheinerman** [ci-group/revolve#21]
- [ ] Add Thymio module to Gazebo (2D)
- [x] Add Thymio module to Gazebo (3D)
- [x] Demo to add Thymio to Gazebo
- [ ] Add multiple robots to same Gazebo environment ("Evert style")
- [ ] One arena per robot ("Jacqueline style")
- [ ] Multiroom environment
- [ ] Maze environment

**Comment by zenfiric** [comment]
The DREAM project has finalised. Not relevant.
