### ISSUE TITLE
Refactoring for a fresh start (27-31 August 2018)

### ISSUE THREAD

**Issue by zenfiric** [ci-group/revolve#4]
The most urgent TODO list:
- [x] Add `RLPower` back as a learning mechanism
- [x] Strip-off Revolve from TOL and Brain
- [x] Test it on Mac and Linux
- [x] Install instructions
- [x] Make Beginner’s tutorials
- [x] Lint
- [x] Docker
- [x] Remove `body-analyzer`
- [x] Debugging errors
- [ ] Multrun Gazebo

**Comment by portaloffreedom** [comment]
What about snapshots, are those really usefull? Or is it other stuff that we can remove?

**Comment by zenfiric** [comment]
The snapshots should be useful. They record the current state of the simulation, so if it breaks, you can always continue from the last recorded state.

**Comment by zenfiric** [comment]
Python tests are added and `refactoring` is merged to `master` branch. Still, C++ and a lot of Python tests are missing.

**Comment by zenfiric** [comment]
This issue is completed. I will close it.
